exclude_paths:
  - 'frontend/express/public/javascripts/dom/**'
  - 'frontend/express/public/javascripts/min/**'
  - 'frontend/express/public/javascripts/utils/**'
  - 'frontend/express/public/javascripts/visualization/**'
  - 'frontend/express/public/localization/**'
  - 'frontend/express/public/fonts/**'
  - 'frontend/express/public/images/**'
  - 'frontend/express/public/stylesheets/amaranjs/**'
  - 'frontend/express/public/stylesheets/font-awesome/**'
  - 'frontend/express/public/stylesheets/ionicons/**'
  - 'frontend/express/public/stylesheets/material/**'
  - 'frontend/express/public/stylesheets/selectize/**'
  - 'bin/backup/**'
  - 'bin/upgrade/**'
  - 'bin/**'
  - 'plugins/*/tests.js'
  - 'plugins/*/tests/**'
  - 'plugins/*/frontend/public/localization/**'
  - 'plugins/*/frontend/public/images/**'
  - 'test/**' 