exclude_paths:
  - 'frontend/express/public/javascripts/dom/**'
  - 'frontend/express/public/javascripts/min/**'
  - 'frontend/express/public/javascripts/utils/**'
  - 'frontend/express/public/javascripts/visualization/**'
  - 'test/**' 