version: "3.7"

volumes:
  mongodb_data:

networks:
  countly:

services:
  mongodb:
    image: 'bitnami/mongodb:3.6.14'
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_DATABASE
    volumes:
      - 'mongodb_data:/bitnami'
    networks:
      countly:

  countly-api:
    image: 'countly/api:19.08.1'
    environment:
      - COUNTLY_CONFIG_API_MONGODB_HOST=mongodb
      - COUNTLY_CONFIG_API_MONGODB_USERNAME=${MONGODB_USERNAME}
      - COUNTLY_CONFIG_API_MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - COUNTLY_CONFIG_API_MONGODB_DB=${MONGODB_DATABASE}
      - COUNTLY_CONFIG_FRONTEND_MONGODB_HOST=mongodb
      - COUNTLY_CONFIG_FRONTEND_MONGODB_USERNAME=${MONGODB_USERNAME}
      - COUNTLY_CONFIG_FRONTEND_MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - COUNTLY_CONFIG_FRONTEND_MONGODB_DB=${MONGODB_DATABASE}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      countly:
    depends_on:
      - mongodb

  countly-frontend:
    image: 'countly/frontend:19.08.1'
    environment:
      - COUNTLY_CONFIG_API_MONGODB_HOST=mongodb
      - COUNTLY_CONFIG_API_MONGODB_USERNAME=${MONGODB_USERNAME}
      - COUNTLY_CONFIG_API_MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - COUNTLY_CONFIG_FRONTEND_MONGODB_HOST=mongodb
      - COUNTLY_CONFIG_FRONTEND_MONGODB_USERNAME=${MONGODB_USERNAME}
      - COUNTLY_CONFIG_FRONTEND_MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - COUNTLY_CONFIG_FRONTEND_MONGODB_DB=${MONGODB_DATABASE}
    networks:
      countly:
    depends_on:
      - mongodb
    deploy:
      # There is usually no need in multiple frontends, so throttling down resources for it
      mode: global
      resources:
        limits:
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    image: 'bitnami/nginx'
    ports:
      - '8080:8080'
    volumes:
      - './bin/docker/nginx.server.conf:/opt/bitnami/nginx/conf/server_blocks/countly.conf:ro'
    networks:
      countly:
    depends_on:
      - countly-api
      - countly-frontend
