apiVersion: apps/v1
kind: Deployment
metadata:
  name: countly-api-deployment
spec:
  selector:
    matchLabels:
      app: countly-api
  replicas: 2
  template:
    metadata:
      labels:
        app: countly-api
    spec:
      containers:
      - name: countly-api
        image: countly/api:19.08.1
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /o/ping
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
          - name: COUNTLY_PLUGINS
            value: "mobile,web,desktop,plugins,density,locale,browser,sources,views,enterpriseinfo,logger,systemlogs,errorlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,assistant,plugin-upload,times-of-day,compliance-hub,video-intelligence-monetization,alerts,onboarding"
          - name: COUNTLY_CONFIG_API_MONGODB
            value: "mongodb://db-mongodb-replicaset-0.db-mongodb-replicaset:27017,db-mongodb-replicaset-1.db-mongodb-replicaset:27017,db-mongodb-replicaset-2.db-mongodb-replicaset:27017/countly?replicaSet=rs0"
          - name: COUNTLY_CONFIG_FRONTEND_MONGODB
            value: "mongodb://db-mongodb-replicaset-0.db-mongodb-replicaset:27017,db-mongodb-replicaset-1.db-mongodb-replicaset:27017,db-mongodb-replicaset-2.db-mongodb-replicaset:27017/countly?replicaSet=rs0"
